### ISSUE TITLE
텍스트가 너무 길때는 말줄임표로 표시하기

### ISSUE THREAD

**Issue by SeonHyungJo** [SeonHyungJo/sNyung-Tip-Note#54]
```html
<p class="ellipsis-text">If I exceed one line's width, I will be truncated.</p>
```

```css
.ellipsis-text {
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
  width: 200px;
}
```

![image](https://user-images.githubusercontent.com/24274424/73319823-db41ef80-4280-11ea-9b77-d9d8c3d7e695.png)
